// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://amuxfuexzmzplcpwsqzj.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdXhmdWV4em16cGxjcHdzcXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk1NDYwODMsImV4cCI6MjA0NTEyMjA4M30.9YQt17JJLBIamRBs4Z0QiIDSjDF65NHGBoUDa5PfL3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);